# JaxWatch Data Sources Configuration
# All municipal data sources and their collection parameters

sources:
  - id: planning_commission
    name: "Planning Commission"
    type: agenda
    url: "https://www.jacksonville.gov/departments/planning-and-development/planning-commission.aspx"
    cadence: weekly
    importance: critical
    enabled: true
    adapter: planning_commission_adapter
    description: "Zoning decisions, land use changes, development approvals"

  - id: infrastructure_committee
    name: "Infrastructure Committee"
    type: agenda
    url: "https://maps.coj.net/capitalprojects/"
    cadence: weekly
    importance: normal
    enabled: true
    adapter: infrastructure_adapter
    description: "Capital improvement projects, transportation, utilities"

  - id: private_development
    name: "Private Development Notices"
    type: notice
    url: "https://jaxepics.coj.net/"
    cadence: daily
    importance: critical
    enabled: true
    adapter: private_development_adapter
    description: "Building permits, development applications, inspections"

  - id: public_projects
    name: "Public Projects"
    type: project
    url: "https://www.jacksonville.gov/departments/"
    cadence: weekly
    importance: normal
    enabled: true
    adapter: public_projects_adapter
    description: "Parks, recreation, municipal facilities, public works"

  - id: city_council
    name: "City Council"
    type: agenda
    url: "https://www.jacksonville.gov/departments/city-council/meetings.aspx"
    cadence: weekly
    importance: critical
    enabled: true
    adapter: city_council_adapter
    description: "Ordinances, budget decisions, policy changes"

  - id: ddrb
    name: "Downtown Development Review Board"
    type: agenda
    url: "https://www.jacksonville.gov/departments/planning-and-development/downtown-development-review-board.aspx"
    cadence: monthly
    importance: normal
    enabled: true
    adapter: ddrb_adapter
    description: "Downtown development project reviews, design standards"

# Future sources (disabled for MVP)
  - id: environmental_board
    name: "Environmental Protection Board"
    type: agenda
    url: "https://www.jacksonville.gov/departments/planning-and-development/environmental-protection-board.aspx"
    cadence: monthly
    importance: normal
    enabled: false
    adapter: environmental_adapter
    description: "Environmental impact reviews, conservation projects"

# Configuration metadata
config:
  schema_version: "2.0"
  last_updated: "2025-09-20"
  default_timeout: 30
  retry_attempts: 3
  alert_on_failure: true
  validate_schema: true