name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pydantic PyYAML requests
          pip install ruff

      - name: Schema smoke tests
        run: |
          python - << 'PY'
          from backend.core.agenda_schema import validate_agenda_item
          # Missing address should flag true, but not drop
          item = {'board': 'Test', 'date': '2025-09-20', 'title': 'No address'}
          v = validate_agenda_item(item)
          assert v.flagged is True
          print('✅ AgendaItem flags missing address as expected')
          PY

      - name: Adapter/sources mapping tests
        run: |
          python - << 'PY'
          from backend.core.municipal_observatory import load_sources
          from backend.adapters import ADAPTER_REGISTRY
          sources, _ = load_sources()
          source_adapters = {s['adapter'] for s in sources if s.get('enabled', False)}
          registry_adapters = set(ADAPTER_REGISTRY.keys())
          unknown = sorted(a for a in source_adapters if a not in registry_adapters)
          unused = sorted(a for a in registry_adapters if a not in source_adapters)
          assert not unknown, f"Adapters listed in sources.yaml not found in registry: {unknown}"
          assert not unused, f"Adapters in registry with no sources.yaml entry: {unused}"
          print('✅ sources.yaml ↔ adapter registry mapping is consistent')
          PY

      - name: Current suite
        run: |
          python test_current_observatory.py

      - name: Lint (ruff)
        run: |
          ruff check .
