name: Update Planning Commission Data

on:
  schedule:
    # Run every Friday at 2 PM (after typical Planning Commission meetings)
    - cron: '0 14 * * 5'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pdfplumber requests beautifulsoup4

    - name: Download latest Planning Commission agendas
      run: python scripts/fetch_latest_agendas.py

    - name: Extract project data from new PDFs
      run: python scripts/process_new_pdfs.py

    - name: Update website data
      run: python scripts/update_website_data.py

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "🤖 Update Planning Commission data - $(date -I)"
          git push
        fi

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        publish_branch: gh-pages